services:
    # frontend services
    frontend:
        build:
            context: ./frontend
        ports:
            - 80:80
        env_file:
            - .env

    # backend services
    db:
        image: mongo:4.4.11-rc1-focal
        restart: always
        ports:
            - 3005:27017
        # networks:
        #     - mongo-compose-network
        env_file:
            - .env
        volumes:
            - ./.db:/data

    mongo-express:
        image: mongo-express:1.0.0-alpha
        restart: always
        ports:
            - 8081:8081
        # networks:
        #     - mongo-compose-network
        env_file:
            - .env
        depends_on:
            - db

    express:
        build:
            context: ./backend/express
        ports:
            - 3001:3001
        env_file:
            - .env
        depends_on:
            - db
        volumes:
            - ./.public:/dist/public

    socket:
        build:
            context: ./backend/socket
        ports:
            - 3002:3002
        env_file:
            - .env
        depends_on:
            - express