FROM node:lts-alpine as build-stage
# FROM node:14-buster-slim as build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

EXPOSE 3002
CMD [ "node", "dist/main.js" ]

